accounts/urls.py
from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', account_views.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

]

products/urls.py
from django.urls import path, include
from .views import HomeView, ProductDetailView
from orders.views import add_to_cart, remove_from_cart, remove_single_item_from_cart, OrderSummaryView

app_name = 'products'

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),

]

uniforms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from products.views import checkoutpage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('checkout/', checkoutpage, name='checkoutpage'),
    path('', include('products.urls', namespace='orders')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
CATEGORY_CHOICES = (             # creating categories of uniforms
    ('B', 'boys'),
    ('G', 'girls')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=1)
    price = models.FloatField()
    slug = models.SlugField()
    description = models.TextField(default='This is my description')
    image = models.ImageField(default='images.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products:product-page", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("orders:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("orders:remove-from-cart", kwargs={
            'slug': self.slug
        })

products/views.py
from django.shortcuts import render
from .models import Item
from django.views.generic import ListView, DetailView
from django.http import HttpResponse


# Create your views here.
class HomeView(ListView):
    model = Item
    template_name = 'products/home.html'
    context_object_name = 'products'  # name to be used to loop over all products


class ProductDetailView(DetailView):
    model = Item
    template_name = 'products/products.html'

def checkoutpage(request):
    return render(request, "accounts/check_out.html")

products/templates/products/includes/footer.html
<div class="clearfix"></div>
<footer id="site-footer">
  <div class="container">

    <div class="footer-nav">
      <ul class="foot-nav">
        <li><a href="#" title="">Bag</a></li>
        <li><a href="#" title="">Belt</a></li>
        <li><a href="#" title="">Boots</a></li>
        <li><a href="#" title="">T-Shirt</a></li>
        <li><a href="#" title="">Shoes</a></li>
        <li><a href="#" title="">Skirt</a></li>
        <li><a href="#" title="">Tie</a></li>
      </ul>
    </div>

    <div class="footer-logo-coppyright">
      <img src="images/logo/easyshop.png"   class="img-responsive" alt="">
    </div>


    <div class="footer-credit">
      <p>Designed with Django by Jeff James</p>
    </div>
  </div>
</footer>
<div class="easyshop-progress-container">
  <div class="easyshop-progress"></div>
</div>

products/templates/products/includes/messages.html
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}

products/templates/products/includes/navbar.html
{% load cart_template_tags %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container">

    <div class="col-sm-4">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Online Shop</a>
      </div>
    </div>

    <div class="col-xs-12 col-sm-8">
      <div class="collapse navbar-collapse navbar-ex1-collapse responsive-menu">
        <ul class="nav navbar-nav">
            {% if request.user.is_authenticated %}
               <li>
                   <a href="{% url 'accounts:logout' %}">Log Out</a>
               </li>
                <li>
                    <a href="{% url 'products:order-summary' %}">{{ request.user|cart_item_count }}
                      <i class="fas fa-shopping-cart"></i>
                       Cart
                    </a>
                </li>
                    {% else %}
                    <li >
                        <a href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:signup' %}">Sign Up</a>
                      </li>
            {% endif %}
        </ul>
      </div>
    </div>

  </div>
</nav>