accounts/urls.py
from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', account_views.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

]

products/urls.py
from django.urls import path, include
from .views import HomeView, ProductDetailView
from orders.views import add_to_cart, remove_from_cart, remove_single_item_from_cart, OrderSummaryView

app_name = 'products'

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),

]

uniforms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from products.views import checkoutpage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('checkout/', checkoutpage, name='checkoutpage'),
    path('', include('products.urls', namespace='orders')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from products.models import Item
from django.contrib.auth.models import User
from django.shortcuts import reverse


# Create your models here.
class OrderItem(models.Model):     # the shopping cart
    item = models.ForeignKey(Item, on_delete=models.CASCADE)     # relationship with item model
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price


class Order(models.Model):          # to link all ordered items (shopping cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)        # to add the order items into the order table
    start_date = models.DateTimeField(auto_now_add=True)    # date the order was created
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

    

orders/views.py
from django.shortcuts import render
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import reverse, redirect, get_object_or_404
from products.models import Item
from orders.models import OrderItem, Order
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("orders:order-summary")
        else:
            order.items.add(order_item)
            messages.success(request, "This item was added to your cart.")
            return redirect("orders:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("orders:order-summary")


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("orders:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("orders:order-summary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("orders:order-summary")


def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("orders:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("orders:order-summary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("orders:order-summary")


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'orders/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, 'You currently do no have any order')
            return render("/")

orders/templates/orders/order_summary.html
{% extends "products/header.html" %}
{% block content %}

    <div class="container">
        <table class="table table-hover">
            <thead>
              <tr>
                <th> </th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total price</th>
              </tr>
            </thead>
            <tbody>
            <!--  .all is used because its a many to many field-->
            {% for order_item in object.items.all %}
                  <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{order_item.item.title}}</td>
                      <td>{{order_item.item.price}}</td>
                      <td>
                          <a href="{% url 'orders:remove-single-item-from-cart' order_item.item.slug %}">
                              <b class="btn btn-sm btn-success"> < </b></a>
                            {{order_item.quantity}}
                          <a href="{% url 'orders:add-to-cart' order_item.item.slug %}">
                              <b class="btn btn-sm btn-success">  > </b></a>
                      </td>
                      <td>Ksh {{ order_item.get_total_item_price }}
                         <a style="color:red;" href="{% url 'orders:remove-from-cart' order_item.item.slug %}">
                             &nbsp;&nbsp;&nbsp;Remove
                         </a>
                      </td>
                  </tr>
                <!-- if the cart is empty-->
            {% empty %}
                <tr>
                    <td colspan="5"><b>Your cart is empty</b></td>
                </tr>
                <tr>
                    <td colspan="5">
                          <a class="btn btn-success float-left" href="/">CONTINUE SHOPPING</a>
                    </td>
                </tr>
            {% endfor %}
            {% if object.get_total %}
                  <tr>
                      <td></td><td></td>
                      <td colspan="2"><b>The Grand Total is</b></td>
                      <td><b>Ksh {{ object.get_total }}</b></td>
                  </tr>
                <tr>
                    <td colspan="5">
                          <a class="btn btn-success float-left" href="/">CONTINUE SHOPPING</a>
                          <a class="btn btn-warning offset-6" href="{% url 'checkoutpage' %}">PROCEED TO CHECK OUT</a>
                    </td>
                </tr>
            {% endif %}
            </tbody>
          </table>
    </div>

{% endblock content %}